### ISSUE TITLE
eth-tester 0.1.0b5 has requirement cytoolz==0.8.2, but you'll have cytoolz 0.9.0.1 which is incompatible.

### ISSUE THREAD

**Issue by drandreaskrueger** [ethereum/eth-tester#108]
could this strict requirement be made more generous?

```
pip install -r requirements.txt
...
eth-tester 0.1.0b5 has requirement cytoolz==0.8.2, but you'll have cytoolz 0.9.0.1 which is incompatible.
...
```

also [related to the same issue as yesterday](https://github.com/ethereum/web3.py/issues/908) --> https://github.com/energywebfoundation/bond/issues/6 "dependencies: eth-tester 0.1.0b5 has requirement cytoolz==0.8.2, but you'll have cytoolz 0.9.0.1 which is incompatible. "

thanks

**Comment by pipermerriam** [comment]
https://github.com/ethereum/eth-tester/blob/master/setup.py#L61

`eth-tester` has the `cytoolz` dependency pinned as `"cytoolz>=0.8.2,<1.0.0;implementation_name=='cpython'"`

Something else must be specifying the exact cytoolz dependency.

**Comment by carver** [comment]
Beta 5 is very old, and does (incorrectly) pin to an exact cytoolz version. Upgrade to the latest with `pip install -U eth-tester` @drandreaskrueger

**Comment by pipermerriam** [comment]
Good catch @carver didn't see the `b5` in the title.

**Comment by drandreaskrueger** [comment]
good, that might help the guys over there https://github.com/energywebfoundation/bond/issues/6 to sort out their non-working requirements.txt

thanks
