### ISSUE TITLE
MoackBackend returned hash value can't found valid trans

### ISSUE THREAD

**Issue by wanpixiaozi** [ethereum/eth-tester#126]
* Version:  0.1.0b32
* Python: 3.5
* OS: win

### What was wrong?
I got below error:

```
Traceback (most recent call last):
  File "D:\eth-tester\eth_tester\backends\mock\main.py", line 244, in get_transaction_receipt
    receipt = self.receipts[transaction_hash]
KeyError: b'\xf3\xbc\xde#\xb2U\x05H\xe0\x98.\xae\xb5}\xb3\x80!\xd4\xca\x0f6\xd8\xc9\xb1\x05\xa3<&\x9eR\x91\x9b'
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "D:/eth-tester/sample.py", line 10, in <module>
    print(t.get_transaction_receipt('0xf3bcde23b2550548e0982eaeb57db38021d4ca0f36d8c9b105a33c269e52919b'))
  File "D:\eth-tester\eth_tester\main.py", line 307, in get_transaction_receipt
    raw_receipt = self.backend.get_transaction_receipt(raw_transaction_hash)
  File "D:\eth-tester\eth_tester\backends\mock\main.py", line 247, in get_transaction_receipt
    "No transaction found for hash: {0}".format(transaction_hash)
eth_tester.exceptions.TransactionNotFound: No transaction found for hash: b'\xf3\xbc\xde#\xb2U\x05H\xe0\x98.\xae\xb5}\xb3\x80!\xd4\xca\x0f6\xd8\xc9\xb1\x05\xa3<&\x9eR\x91\x9b'

Process finished with exit code 1
```

### My code is below:

```python
from eth_tester import EthereumTester, MockBackend


t = EthereumTester(MockBackend())
print(t.get_accounts())
print(t.get_balance('0xaBbACadABa000000000000000000000000000000'))
print(t.send_transaction({'from': '0x82A978B3f5962A5b0957d9ee9eEf472EE55B42F1', \
                          'to': '0x7d577a597B2742b498Cb5Cf0C26cDCD726d39E6e', 'gas': 21000, 'value': 1}))
print(t.get_transaction_receipt('0xf3bcde23b2550548e0982eaeb57db38021d4ca0f36d8c9b105a33c269e52919b'))
```

### How can it be fixed?

I wonder if this issue only exist on MockBackend or on PyEVM both?

**Comment by wanpixiaozi** [comment]
I modified test sample to below and found issue fixed
from eth_tester import EthereumTester, MockBackend


t = EthereumTester(MockBackend())
# t = EthereumTester()

res_hash = t.send_transaction({'from': '0xaBbACadABa000000000000000000000000000000', \
                          'to': '0x82A978B3f5962A5b0957d9ee9eEf472EE55B42F1', 'gas': 21000, 'value': 1000})
print(res_hash)
print(t.get_transaction_receipt(res_hash))

**Comment by wanpixiaozi** [comment]
thanks a lot, i used returned value to check immediately, and found issue solved, as the returned value only can be used at one process, not real chain.


________________________________
发件人: Piper Merriam <notifications@github.com>
发送时间: 2018年9月17日 18:25
收件人: ethereum/eth-tester
抄送: wanpixiaozi; Mention
主题: Re: [ethereum/eth-tester] MoackBackend returned hash value can't found valid trans (#126)


@wanpixiaozi<https://github.com/wanpixiaozi> You're sample code has a hard coded transaction hash. Does that hash match the one which is printed on the previous t.send_transaction line?

―

**Comment by pipermerriam** [comment]
@wanpixiaozi please take some time to read https://guides.github.com/features/mastering-markdown/ so that you can format your code blocks in a more legible manner.

**Comment by wanpixiaozi** [comment]
thanks, i would use markdown format next time
