### ISSUE TITLE
Update gas limit

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/eth-tester#147]
### What was wrong?
Current default block gas limit is 3.14m gas. Mainchain gas limit has been around 8m for a while now, which means it is possible to deploy larger contracts than what is currently testable. Lowest testnet block gas limit is 7m gas.

### How can it be fixed?

Until #129 is implemented to permanently solve the configuration issue, I would suggest that the arbitrarily-chosen default be at least 2x'd to 6.28m gas (2 Pi). This would ensure a more realistic block gas limit for testing, while retaining a sufficient margin of safety against the current limits (which can fluctuate slightly)

**Comment by pipermerriam** [comment]
I'm :+1: on this.

**Comment by MatthiasLohr** [comment]
Any news on that?
