### ISSUE TITLE
Is there way I can create long lived chain?

### ISSUE THREAD

**Issue by NikitaMishin** [ethereum/eth-tester#155]
* Version: x.x.x
* Python: 2.7/3.4/3.5
* OS: osx/linux/win

### What was wrong?
Sorry for silly question, but could I create long lived Blockchain? I.e I want to save state between launches.
* The code which produced the error
* The full output of the error

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by reedsa** [comment]
I assume this.can be closed after all this time. For posterity, the ganache-cli is capable of taking snapshots and reloading from them.

See the [ganache-cli](https://github.com/trufflesuite/ganache) repo for more info.

Feel free to raise a new issue if there are any other questions.
