### ISSUE TITLE
Upgrade to latest py-evm, v0.2.0-alpha.43

### ISSUE THREAD

**Issue by carver** [ethereum/eth-tester#157]
### What was wrong?

Don't have the latest features, bugfixes, performance improvements, etc from py-evm yet.

### How can it be fixed?

Upgrade py-evm to the latest in setup.py, and fix and problems that come up in the CircleCI run. (See #158 for the circle failures)

**Comment by palango** [comment]
Seems like this update was done, but an update to the Istanbul enabled `py-evm` would be nice nevertheless. 😋

**Comment by carver** [comment]
#165
