### ISSUE TITLE
Gas limit is not constant

### ISSUE THREAD

**Issue by berndbohmeier** [ethereum/eth-tester#186]
### What was wrong?
I try to set the gas_limit in the genesis block. This works, but if I now mine blocks the gas limit changes, where I would expect it to not change. 

```
genesis_parameters = get_default_genesis_params({"gas_limit": 8 * 10 ** 6})
chain = eth_tester.EthereumTester(
        eth_tester.PyEVMBackend(genesis_parameters=genesis_parameters)
    )
for _ in range(1000):
    chain.mine_block()
assert web3.eth.getBlock("latest").gasLimit == 8 * 10 ** 6
```

### How can it be fixed?
Copy the gas limit from the old block. I can prepare an PR for that, but first I want to check if you would accept that, as it could be that some are relying on the changing gas_limit.

**Comment by pipermerriam** [comment]
I'm not sure why the gas limit is changing. I believe that a *constant* gas limit would be preferred.

**Comment by berndbohmeier** [comment]
I think it uses the default behavior from pyevm, which should be this https://github.com/ethereum/py-evm/blob/master/eth/_utils/headers.py#L30 if I am not mistaken.
That would explain why I see it decreasing for empty blocks.

**Comment by berndbohmeier** [comment]
Should be fixed.
