### ISSUE TITLE
Improve testing of gas estimation with block identifiers

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/eth-tester#190]
### What was wrong?
PR https://github.com/ethereum/eth-tester/pull/189 introduced support for block identifiers (e.g., "latest", "earliest") in the `estimateGas` method. A "good enough" test was included, but there's lots of room for improvement.

### How can it be fixed?
Cherry-picking from the above-mentioned PR:
@carver: 
> I guess I should have said the best kind of test would be to write a contract that burns gas in a way that's easily detectable by block number, like burning (100k * block_number) gas.

@pipermerriam: 
> Contract with a toggle-able flag which just returns immediately or burns a bunch of gas in a loop. Then you can set it and test on either side of the block number where the flag was toggled.

**Comment by ackhia** [comment]
I created PR #200 to hopefully resolve this.

**Comment by kclowes** [comment]
Closed with #200
