### ISSUE TITLE
getTransaction returns incorrect gas value

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/eth-tester#197]
### What was wrong?

eth-tester appears to store whatever gas value gets passed in with a transaction, rather than the actual gas that was consumed. Web3.py example:

```
w3 = Web3(Web3.EthereumTesterProvider())
tx_hash = w3.eth.sendTransaction({ 'from': w3.eth.accounts[0], 'to': w3.eth.accounts[1], 'value': 1 )}
tx = w3.eth.getTransaction(tx_hash)

print(tx['gas'])
# 121000  (should be 21000)
```

Learnings so far:
- As for the origin of the extra 100k gas, a [buffer is applied within Web3.py](https://github.com/ethereum/web3.py/blob/08ff156c071eb4486017b7e035d30a08750e927f/web3/_utils/transactions.py#L123) when a gas value isn't specified. 
- This appears to be an issue of presentation. If you check the balance of the sending account, appropriately, only 21000 gas is deducted from the balance. 
- chaindb looks right, e.g., `self.chain.chaindb.get_canonical_head()['gas_used'] == 21000`

**Comment by marcgarreau** [comment]
Could use some feedback on this one.

I can "fix" the issue illustrated in the example above by freshly estimating the gas and overwriting the gas value (i.e., `transaction['gas'] = self.estimate_gas(transaction)`) within this function:

https://github.com/ethereum/eth-tester/blob/6d34cf4d066beffa164f9a7766f5b782ebe3d2a4/eth_tester/backends/pyevm/main.py#L451-L460

However, several other tests fail as a result, because the tests expect the original transaction's gas value to be persisted. I can set about updating those tests too, but my concern is that the behavior seems intentional and altering that may have additional consequences in upstream libs, etc. 

I think you may be the best candidate to comment on the intention and bigger picture here @carver - please and thanks!

**Comment by carver** [comment]
Ah, I think I led you astray in chat. `121000` is the correct thing to return from the client when running `eth_getTransactionByHash`.   It just returns the amount of gas supplied by the sender (which as you mentioned, is what web3py did).

It's `eth_getTransactionReceipt` that should only return `21000`.

**Comment by marcgarreau** [comment]
Ah, that is not what I expected. TIL. Re: blog post, will update from getTransaction to getTransactionReceipt. Explaining the difference is probably deeper than Part 1 should go. Thanks for explaining; not a bug, so closing this issue.
