### ISSUE TITLE
Issue with dynamic fee txn properties casing validation

### ISSUE THREAD

**Issue by unparalleled-js** [ethereum/eth-tester#222]
* Version: 0.6.0b1
* Python: 3.9.7
* OS: macOS

### What was wrong?

When specifying `maxPriorityFeePerGas` and `maxFeePerGas` (using expected camelCasing like the other txn values):

```
   eth_tester.exceptions.ValidationError: Only the keys 'access_list/chain_id/data/from/gas/gas_price/max_fee_per_gas/max_priority_fee_per_gas/to/type/value' are allowed.  Got extra keys: 'maxFeePerGas/maxPriorityFeePerGas'
```

**I am using web3 btw**

When specifying them as snake_case, just to see what happens:

```
TypeError: Transaction must not include unrecognized fields: {'max_priority_fee_per_gas', 'max_fee_per_gas'}
```

Validation passes but it fails where you would expect it to.
Seems like there is a bug with validating the txn schema?

### How can it be fixed?

Adjust the validation? I am not sure, but probably look into it

**Comment by unparalleled-js** [comment]
Oh okay, so I am realizing it was likely a fluke that it worked with camelCasing before, for some reason...
And that txns in eth-tester are always expected to have snake_cased keys?

**Comment by fselmo** [comment]
> Oh okay, so I am realizing it was likely a fluke that it worked with camelCasing before, for some reason... And that txns in eth-tester are always expected to have snake_cased keys?

I was in the middle of responding to this but yep! You got it.

**Comment by fselmo** [comment]
I'm going to close this for now. Please feel free to re-open if there is still an issue here.
