### ISSUE TITLE
Legacy properties required and set to null instead of allowed to be excluded

### ISSUE THREAD

**Issue by unparalleled-js** [ethereum/eth-tester#223]
* Version: 0.6.0b1
* Python: 3.9.7
* OS: macOS

### What was wrong?

When using the dynamic fee model for txns, you still have to make sure `gasPrice` is present in the data (and set to `None`).
That does not seem necessary and interferes with object-oriented modeling of both types of transactions.

### How can it be fixed?

If it is required, from an API perspective, it would be nice to do add the key / empty-value automatically.
Otherwise, adjust the validation to not care if that key is missing.

**Comment by fselmo** [comment]
I'm assuming this is related to the camelCase issue that was raised this morning as well. You should not need a `None` `gas_price` when sending `max_fee_per_gas` and `max_priority_fee_per_gas`. @unparalleled-js are you still having issues if you use snake_case params?

**Comment by unparalleled-js** [comment]
@fselmo I believe my issues are related to the web3 eth-tester middleware actually! We can close this one too, I can reopen if my investigation brings me back here. Thank you!
