### ISSUE TITLE
Problems with PyEVMBackend Berlin configuration

### ISSUE THREAD

**Issue by MetaB0y** [ethereum/eth-tester#237]
* Version: 0.6.0b6
* Python: 3.10.5
* OS: osx

## What is wrong

I am trying to update Uniswap-v1 libraries (https://github.com/Uniswap/v1-contracts) to the newest versions.

In tests/conftest.py there is `EthereumTester(backend=PyEVMBackend())`

It breaks tests now because Ethereum moved to post-London, and there is base_fee_per_gas. So I get `eth_utils.exceptions.ValidationError: Sender's max fee per gas (0) is lower than block's base fee per gas (875000000)`. This is unrelated, but if somebody could tell me how to set the gas to 0 in London, I would be very grateful.

What is related is that another way to fix this issue is to is to use another fork, e.g. Berlin.

So I tried
```
EthereumTester(backend=PyEVMBackend(
        vm_configuration=(
            (0, BerlinVM),
        )
    ))
 
```

Unfortunately, it fails with the following error
```
env/lib/python3.10/site-packages/web3/providers/eth_tester/defaults.py:66: in call_eth_tester
    return getattr(eth_tester, fn_name)(*fn_args, **fn_kwargs)
env/lib/python3.10/site-packages/eth_tester/main.py:456: in call
    raw_result = self.backend.call(raw_transaction, raw_block_number)
env/lib/python3.10/site-packages/eth_tester/backends/pyevm/main.py:654: in call
    signed_evm_transaction = self._get_normalized_and_signed_evm_transaction(
env/lib/python3.10/site-packages/eth_tester/backends/pyevm/main.py:565: in _get_normalized_and_signed_evm_transaction
    evm_transaction = self._create_type_aware_unsigned_transaction(normalized_transaction)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <eth_tester.backends.pyevm.main.PyEVMBackend object at 0x106a408e0>
normalized_txn = {'access_list': (), 'chain_id': 131277322940537, 'data': b'\x06\xf2\xbfb\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf2\xe2F\xbbv\xdf\x87l\xef\x8b8\xae\x84\x13\x0fOU\xde9[', 'gas': 1000000000, ...}

    def _create_type_aware_unsigned_transaction(self, normalized_txn):
        if all(_ in normalized_txn for _ in ("access_list", "gas_price")):
            return self.chain.get_transaction_builder().new_unsigned_access_list_transaction(
                **normalized_txn
            )
        elif all(_ in normalized_txn for _ in DYNAMIC_FEE_TRANSACTION_PARAMS):
>           return self.chain.get_transaction_builder().new_unsigned_dynamic_fee_transaction(
                **normalized_txn
            )
E           AttributeError: type object 'BerlinTransactionBuilder' has no attribute 'new_unsigned_dynamic_fee_transaction'

env/lib/python3.10/site-packages/eth_tester/backends/pyevm/main.py:574: AttributeError
```

**Comment by fselmo** [comment]
Hey @MetaB0y. The issue you're seeing using Berlin is that Berlin had no support for `maxFeePerGas` and `maxPriorityFeePerGas` so your transactions will have to use `gasPrice`.

> This is unrelated, but if somebody could tell me how to set the gas to 0 in London

I'm not sure at all of our context but it seems like you are wanting to use pre-London rules, in which case setting to Berlin and using `gasPrice` and removing `maxFeePerGas` and `maxPriorityFeePerGas` from your transactions might resolve it. But I'm not sure without more context what exactly you're wanting to do.
