### ISSUE TITLE
feat: Python 3.12 support

### ISSUE THREAD

**Issue by BoboTiG** [ethereum/eth-tester#276]
Hello team,

This part of the code is failing on Python 3.12:

https://github.com/ethereum/eth-tester/blob/3c76d34beb3ade64ec4569462b36351bdb9a0821/eth_tester/backends/pyevm/utils.py#L5

Do you plan to work on Python 3.12 support (maybe are you already working on it? 🤞🏻 😈)?

**Comment by pacrob** [comment]
Definitely planning to! Not started yet, but Coming Soon :tm: 

Thanks for the poke.
