### ISSUE TITLE
Validate Transaction Function Doesnt allow for chainId

### ISSUE THREAD

**Issue by dangell7** [ethereum/eth-tester#56]
* Version: 0.1.0b13
* Python: 3.5
* OS: linux

### What was wrong?

The validate_transaction function does not allow for chainId as a parameter. When I ran a test using web3.py to send a transaction that included the chainId as a parameter, I received the following error. 

eth_tester.exceptions.ValidationError: Only the keys 'data/from/gas/gas_price/nonce/to/value' are allowed.  Got extra keys: 'chainId'

ethereum/web3.py/pull/595

### How can it be fixed?

Add chainId to the inbound.py and oubound.py validation functions.

**Comment by dangell7** [comment]
@carver you fix this?

**Comment by carver** [comment]
Nope, it's just on my to-do list. If you want to take a crack at it, go ahead @dangell7

**Comment by dangell7** [comment]
I sure do!! lol

**Comment by dangell7** [comment]
@carver What IDE do you use? I use pycharm and the renew is coming up. Plus I'm noticing that my merges don't quite work with lint/travis so I was curious.

**Comment by carver** [comment]
> I sure do!! lol

@dangell7 heh, great, I'm happy to review.

> What IDE do you use?

I'm in `vim`. It's nice after all the pain.

> I'm noticing that my merges don't quite work with lint/travis

I usually just have a pre-commit hook that runs `flake8` for me (and `isort` in web3.py).

**Comment by dangell7** [comment]
@carver I'm I got really busy and couldn't figure it out. I'm sorry. I'll keep working on it.

**Comment by carver** [comment]
@dangell7 let me know if you have to drop this, and I'll put it back in my queue. Not sure how long it will take me to get to it.

**Comment by carver** [comment]
@dangell7 Any update? If I don't hear back by Thur, Feb 15, I'll take it on sometime after that. We're getting several incoming requests to make this happen.

**Comment by carver** [comment]
Hm, actually, looking at this with a fresh pair of eyes, I think a better approach would be to solve this on the web3.py side. `chainId` is kind of something you only care about during local signing, it's not a standard transaction field in json-rpc for example.

I'm thinking web3.py should have a middleware that validates the chainId is the same as the network ID that the node is on, then remove the chainId from the transaction.

**Comment by carver** [comment]
> I'm thinking web3.py should have a middleware that validates the chainId is the same as the node connected to, then remove the chainId from the transaction.

In practice: https://github.com/ethereum/web3.py/pull/656

**Comment by pipermerriam** [comment]
closing in favor of web3 level solution.
