### ISSUE TITLE
Handle pending transactions with a tx pool

### ISSUE THREAD

**Issue by monokh** [ethereum/eth-tester#59]
* Version: 0.1.0-beta.16
* Python: all
* OS: all

### What was wrong?

Eth tester does not handle pending transactions correctly when disabling auto mining transactions:

Sending a transaction with the same nonce causes an invalid nonce error:

```
from eth_tester import (
    EthereumTester,
    PyEVMBackend,
)

backend = PyEVMBackend()
t = EthereumTester(backend=backend)
t.disable_auto_mine_transactions()
accounts = t.get_accounts()
tx = t.send_transaction({'from': accounts[0], 'to': accounts[1], 'gas': 21000, 'value': 1, 'nonce': 0})
tx2 = t.send_transaction({'from': accounts[0], 'to': accounts[1], 'gas': 21000, 'value': 1, 'nonce': 0})
>>> evm.exceptions.ValidationError: Invalid transaction nonce
```
### How can it be fixed?

The issue is that `send_transaction` and `send_raw_transaction` immediately execute on the vm's state and thereby increment the valid nonce.

### Things to consider for the fix:

- A tx pool needs to be managed at the eth tester level
- It should consider the rules for replacing transactions. e.g. transactions with existing nonce should overwrite #57 
- Will the tx pool work for every backend? 
- `eth-tester` exposes both `send_transaction` and `send_raw_transaction` both of which have different code paths. We need to ensure that we treat them the same as far as the tx pool is concerned.  
- `eth-tester` does not know about the outcome of a transaction (e.g. for figuring out what nonce a transaction will execute at). Could circumvent this by using `get_transaction_by_hash` after executing the transaction.

A very rudimentary fix: 
```
if self.auto_mine_transactions:
    self.mine_block()
else:
    snapshot = self.take_snapshot()
    # If a pending transaction with the same nonce exists, overwrite it?
    self._pending_transactions.append(transaction)
    self.revert_to_snapshot(snapshot)

def enable_auto_mine_transactions(self):
    self.auto_mine_transactions = True
    return [self.send_transaction(tx) for tx in self._pending_transactions]
```

@carver @pipermerriam feel free to modify the issue to clarify things 🙂

**Comment by carver** [comment]
> Could circumvent this by using get_transaction_by_hash after executing the transaction

This also seems like a good way to avoid having to parse the raw transaction locally (to identify the nonce).

**Comment by carver** [comment]
```py
            # If a pending transaction with the same nonce exists, overwrite it?
            self._pending_transactions.append(transaction)
```
Yes, we should never have two transactions with the same nonce in the pending list. If the new one raises an exception during execution (for example, if its gas price is too low), then leave the old pending in place. If the new execution succeeds (before rollback), then remove the old transaction at the same nonce, and insert the new pending one.

```py
if not self.auto_mine_transactions:
            snapshot = self.take_snapshot()

### actual transaction execution presumably happens here

if self.auto_mine_transactions:
```

**Comment by pipermerriam** [comment]
I made a small adjustment to your code block.  Overall looks like a solid approach.  Lets see how it shakes out during implementation.
