### ISSUE TITLE
Mock storage variables in contracts?

### ISSUE THREAD

**Issue by jstoxrocky** [ethereum/eth-tester#74]
I was curious as to whether it is theoretically possible to somehow add some functionality to the eth-tester library to mock state variables in contracts? I don't actually know too much about how data is stored in the EVM, and I'm coming from a Solidity mind-set so maybe I'm thinking about storage incorrectly. I was hoping for a reason why, if this is not possible, and maybe a hint of the right direction to start exploring this idea if it should be possible.

I would basically like functionality to do something like:

```solidity
contract Example {
   function getVal() view public returns (uint256) {...}

   function doSomething() view public returns (bool) {
     uint256 x = getVal();
     require(x > 10);
     ...
  }
}
```

```python
def test_contract(contract):
    EthereumTester.mock(contract, 'getVal').return_value = 11
    output = contract.functions.doSomething().call()
    assert output 
```

**Comment by pipermerriam** [comment]
This isn't going to be something that fits well within what `eth-tester` is intended for.  However, in your specific use case, if you need to mock out a contract function, you might do something like the following.

```javascript
contract Example {
   function getVal() view public returns (uint256) {...}

   function doSomething() view public returns (bool) {
     uint256 x = getVal();
     require(x > 10);
     ...
  }
}

contract ExampleForTesting is Example {
  function getVal() view public returns (uint256) { return 11; }
}
```

And then you can just use `ExampleForTesting` in your tests.

**Comment by jstoxrocky** [comment]
@pipermerriam Awesome workaround thank you!
