### ISSUE TITLE
Support nonce in transactions

### ISSUE THREAD

**Issue by zheli** [ethereum/eth-tester#80]
### What was wrong?

When sending transactions from web3.py buildTransaction() with nonce specified, I got  got an error from validate_transaction():
```
    def validate_transaction(value, txn_type):
        if txn_type not in ALLOWED_TRANSACTION_TYPES:
            raise TypeError("the `txn_type` parameter must be one of send/call/estimate")
        if not is_dict(value):
            raise ValidationError("Transaction must be a dictionary.  Got: {0}".format(type(value)))
    
        unknown_keys = tuple(sorted(set(value.keys()).difference(
            TRANSACTION_TYPE_INFO[txn_type],
        )))
        if unknown_keys:
            raise ValidationError(
                "Only the keys '{0}' are allowed.  Got extra keys: '{1}'".format(
                    "/".join(tuple(sorted(TRANSACTION_TYPE_INFO[txn_type]))),
>                   "/".join(unknown_keys),
                )
            )
E           eth_tester.exceptions.ValidationError: Only the keys 'data/from/gas/gas_price/to/value' are allowed.  Got extra keys: 'nonce'
```

### How can it be fixed?

Add support for nonce in transaction. 

This commit should be reverted when the issue is fixed. 
 https://github.com/ethereum/web3.py/pull/743/commits/07c446e4df6f5dd7ece43c922fb8aaeec936265c

**Comment by mikeshultz** [comment]
This appears to have been fixed already?  

    from web3 import Web3, EthereumTesterProvider
    w3 = Web3(EthereumTesterProvider())
    SS_ABI = [{"constant":False,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[],"name":"get","outputs":[{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function"}]
    SS_BYTECODE = "0x608060405234801561001057600080fd5b5060df8061001f6000396000f3006080604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806360fe47b114604e5780636d4ce63c146078575b600080fd5b348015605957600080fd5b5060766004803603810190808035906020019092919050505060a0565b005b348015608357600080fd5b50608a60aa565b6040518082815260200191505060405180910390f35b8060008190555050565b600080549050905600a165627a7a7230582084094454350b469a9ded65c5f5cbedcbfa530048dce0eb1afdec3e138579c4370029"
    SimpleStorage = w3.eth.contract(abi=SS_ABI, bytecode=SS_BYTECODE)

    nonce = w3.eth.getTransactionCount(w3.eth.accounts[0])
    tx_hash = SimpleStorage.constructor().transact({ 'nonce': nonce })
    tx_receipt = w3.eth.waitForTransactionReceipt(tx_hash)

    ss = w3.eth.contract(
        address=tx_receipt.contractAddress,
        abi=SS_ABI,
    )

    ss.functions.set(1).buildTransaction({ 'from': w3.eth.accounts[0], 'nonce': nonce+1 })
    # {'value': 0, 'gas': 45793, 'gasPrice': 1, 'chainId': None, 'from': '0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf', 'nonce': 1, 'to': '0xF2E246BB76DF876Cef8b38ae84130F4F55De395b', 'data': '0x60fe47b10000000000000000000000000000000000000000000000000000000000000001'}
