### ISSUE TITLE
Remove methods from eth_tester.utils.formatting, use eth-utils version instead

### ISSUE THREAD

**Issue by carver** [ethereum/eth-tester#90]
### What was wrong?

There are a number of methods in `eth_tester.utils.formatting` that are better maintained in eth-utils.

### How can it be fixed?

Remove these versions, and replace all usages with the eth-utils ones.

May depend on: https://github.com/ethereum/eth-utils/issues/101

**Comment by mikeshultz** [comment]
Looks like this is pretty much complete.  The only function in use from `eth_tester.utils.formatting` is `replace_exceptions` from #101.

**Comment by carver** [comment]
Nice, that method is also in eth-utils as of v1.1.0: https://eth-utils.readthedocs.io/en/stable/releases.html?highlight=exceptions#id8

So we can convert that usage and delete the whole `formatting` module. :+1:
