### ISSUE TITLE
Accounts are not persisted when using LevelDB

### ISSUE THREAD

**Issue by mateuszk87** [ethereum/eth-tester#95]
* py-evm Version: 0.20.a17
* OS: osx
* Python Version (python --version): 3.6.5
* Environment (output of `pip freeze`): 
..
eth-abi==1.1.1
eth-account==0.2.2
eth-bloom==1.0.0
eth-hash==0.1.2
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-tester==0.1.0b25
eth-utils==1.0.3
hexbytes==0.1.0
..
py-ecc==1.4.2
py-evm==0.2.0a17
pycparser==2.18
pycryptodome==3.6.1
pyethash==0.1.27
Pygments==2.2.0
pypandoc==1.4
pysha3==1.0.2
pytest==3.5.1
python-dateutil==2.7.3
requests==2.18.4
rlp==1.0.1
..

### What was wrong?

When using LevelDB account keys are not persisted:
       
```
       # LevelDB will set all account balances equal to 0
       #db = ChainDB(LevelDB('./testleveldb.db'))

       # MemoryDB correctly persists account balances to 1000000000000000000000000
        db = ChainDB(MemoryDB())

        self.account_keys = get_default_account_keys()
        genesis_state = generate_genesis_state(self.account_keys)
        self.chain = chain_class.from_genesis(db, genesis_params, genesis_state)

```

Testing code to retrieve balances:

```
tester = EthereumTester(backend)
accounts = tester.get_accounts()
print(accounts)
print(list(tester.get_balance(account) for account in accounts))
```

**Comment by pipermerriam** [comment]
If I understand correctly, this is assuming that using `LevelDB` will allow you to persist state and then re-load it again into a new `EthereumTester` instance.  While there is nothing specific to disallow this, it's not currently supported functionality.  Even if this is resolved, you will *likely* still find other things that don't behave as expected as `EthereumTester` maintains statefulness beyond the underlying backend's chain database.

We've talked about adding a formal API for persisting an `EthereumTester` state and then loading that state.

Correct me if I've mis-understood your problem.

**Comment by carver** [comment]
I read this as a `py-evm` report. The claim being that swapping in `LevelDB` for `MemoryDB` in `ChainDB` causes different results to be retrieved, even just after genesis.

**Comment by mateuszk87** [comment]
I wasn't sure if this is a py-evm or eth-tester problem. As a user I assumed that LevelDB and MemoryDB have the same behavior. 

My use case is to use an existing state, which will be used for testing (I don't want to redo the transactions programmatically). In future (when sync with mainnet is working) I would like to use mainnet data, fork off with a new VM (similar to MainnetTesterChain) and then do testing :)

**Comment by mateuszk87** [comment]
I had an dependency issue...
