### ISSUE TITLE
Vyper dependency causing testing errors

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth-tester#99]
* Version: 0.1.0b24/0.1.0b26
* Python: 3.6.5
* OS: osx

### What was wrong?

Testing errors when bumping version of vyper

Reproduce:
- pull down casper master
- in requirements.txt, bump vyper version to most recent commit — 8113f79f7bce362e7a0f803b32736cb460c78640
- install via `pip install -r requirements.txt`
- run `pytest tests`

The above will produce the following error:
```
 TypeError: 'ChainDB' object does not support item assignment
```

If the version of eth-tester is bumped to 0.1.0b26 in addition to the vyper commit bump, running `pytest tests` will produce:
```
evm.exceptions.ValidationError: mix hash mismatch; 0x351006e4ee3e28295bf07ff25dd9fd91d23751e0036fdfc39a51635e0e2edd69 != 0x0000000000000000000000000000000000000000000000000000000000000000
```

### How can it be fixed?
Not sure yet.

**Comment by pipermerriam** [comment]
Culprit was bad dependency management by pip or something causing a newer version of `py-evm` to be install.  Forcing `py-evm==0.2.0a18` fixes this.
